added soo much

diff --git a/local/bin/goc b/local/bin/goc
--- a/local/bin/goc
+++ b/local/bin/goc
@@ -1,13 +1,7 @@
 #!/bin/sh
+[ "$#" -ne 1 ] && echo "Usage: go <GoSourceFile.go>" && exit 1
+input_file="$1"
+output_file="${input_file%.go}.out"
 
-[ "$#" -ne 1 ] && echo "Usage: $0 <file.go>" >&2 && exit 1
-
-i="$1"
-o="${i%.go}.out"
-
-[ -f "$i" ] || {
-	echo "Error: '$i' not found!" >&2
-	exit 1
-}
-
-go build -o "$o" "$i" || exit $?
+[ ! -f "$input_file" ] && echo "Error: '$input_file' not found!" && exit 1
+go build -o "$output_file" "$input_file"
diff --git a/local/bin/rc b/local/bin/rc
--- a/local/bin/rc
+++ b/local/bin/rc
@@ -1,13 +1,7 @@
 #!/bin/sh
+[ "$#" -ne 1 ] && echo "Usage: rc <RustSourceFile.rs>" && exit 1
+input_file="$1"
+output_file="${input_file%.rs}.out"
 
-[ "$#" -ne 1 ] && echo "Usage: $0 <file.rs>" >&2 && exit 1
-
-i="$1"
-o="${i%.rs}.out"
-
-[ -f "$i" ] || {
-	echo "Error: '$i' not found!" >&2
-	exit 1
-}
-
-rustc "$i" -o "$o" || exit $?
+[ ! -f "$input_file" ] && echo "Error: '$input_file' not found!" && exit 1
+rustc "$input_file" -o "$output_file"
